LibPaths = [
    '../ngspice-bin/lib/'
]

env = Environment(CPPPATH=['../ngspice-bin/share/ngspice/include/',
                           '-I/usr/include/python2.7'],
                  CXXFLAGS=['-O2', '-mfpmath=sse', '-msse4', '-march=native',
                            '-Wall', '-g', '-std=c++0x'],
                  LIBS=['boost_python'],
                  LIBPATH=LibPaths,
                  LINKFLAGS=['-pthread'] + map(lambda x: "-Wl,-rpath=%s" % x, LibPaths))

hwcpplib = env.SharedLibrary('hwcpplib',
                             Glob("*.cpp"))
install = env.InstallAs('../hwlib/hwcpplib.so', hwcpplib)

Default(install)